### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by tbroed** [HuanYin94/RaLL#2]
Hi,

I have two questions for testing your pipeline: 

1. Are you planning on releasing a pre-trained model 
2. Which RobotCar run is meant with "seq02" and how do I have to prepare the radar data in order to be used by the pipeline.

Greeting,
Tim

**Comment by HuanYin94** [comment]
> Hi,
> 
> I have two questions for testing your pipeline:
> 
> 1. Are you planning on releasing a pre-trained model
> 2. Which RobotCar run is meant with "seq02" and how do I have to prepare the radar data in order to be used by the pipeline.
> 
> Greeting,
> Tim

Hi Tim,

Thanks for your attention.

1. Yes, I can release a pre-trained model this week.
2. 'Seq02' is the 'Oxford-02' in RaLL paper (Table I), which is collected at 12:32:52 GMT 10/01/2019. Please refer to https://oxford-robotics-institute.github.io/radar-robotcar-dataset/datasets. The radar images are with 512x512 size and 0.25m/pixel resolution, which can be generated by using the RobotCar SDK: https://github.com/ori-mrg/robotcar-dataset-sdk.

In addition, a more concise form of RaLL can also localize the radar on lidar maps. I may release this concise recently.

**Comment by HuanYin94** [comment]
> Hi,
> 
> I have two questions for testing your pipeline:
> 
> 1. Are you planning on releasing a pre-trained model
> 2. Which RobotCar run is meant with "seq02" and how do I have to prepare the radar data in order to be used by the pipeline.
> 
> Greeting,
> Tim

Pre-trained models have been released. Sorry for the late response.

**Comment by HR-zju** [comment]
> Hi,
> 
> I have two questions for testing your pipeline:
> 
> 1. Are you planning on releasing a pre-trained model
> 2. Which RobotCar run is meant with "seq02" and how do I have to prepare the radar data in order to be used by the pipeline.
> 
> Greeting, Tim

Hello, can you reproduce the code effect in the text? I tested with the latest code, but it didn't work very well.

**Comment by HuanYin94** [comment]
> > Hi,
> > I have two questions for testing your pipeline:
> > 
> > 1. Are you planning on releasing a pre-trained model
> > 2. Which RobotCar run is meant with "seq02" and how do I have to prepare the radar data in order to be used by the pipeline.
> > 
> > Greeting, Tim
> 
> Hello, can you reproduce the code effect in the text? I tested with the latest code, but it didn't work very well.

Hi do you use odometry information?
